### ISSUE TITLE
run.py SyntaxError

### ISSUE THREAD

**Issue by duxing0626** [jhs7jhs/ichika-janken-auto#3]
Line 46:
return f'k_{kcsess}_{keys[0]}_{keys[1]}_{keys[2]}_{keys[3]}_{keys[4]}'
^
SyntaxError: invalid syntax

Is this not support python 3.9?

**Comment by duxing0626** [comment]
sorry i fix my problem

**Comment by hyunsikjeong** [comment]
lol, Please search it before asking...
Also, if your problem is resolved, at least leave a comment about what your cause was.

F-string, or Formatted string literals is included in Python3 since version 3.6, as far as I know. [Link](https://docs.python.org/3.6/reference/lexical_analysis.html#formatted-string-literals)
